org: vetocode
app: aws-node-http-api-project
service: mongo-reader-api-lambda
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
